/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: RedMug (https://sketchfab.com/blendeed)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-ps1-base-mesh-df1f2d894d6e4b919a7dd41b42866c5b
Title: Low Poly Ps1 Base Mesh
*/

// import React, { useEffect, useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Astronaut(props) {
//   const { nodes, materials } = useGLTF('/models/low_poly_ps1_base_mesh.glb')
//   return (
//     <group {...props} dispose={null}>
//       <group scale={0.01}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube_Material_0.geometry}
//           material={materials.Material}
//           position={[-264.536, 27.17, 104.999]}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/models/low_poly_ps1_base_mesh.glb')